version: '3.8'

services:
  pytest:
    build: .
    command: pytest --html=./reports/report.html --self-contained-html tests -n auto -vv --no-header
    volumes:
      - ./logs:/app/logs:rw  
      - ./reports:/app/reports:rw 


  

    