# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      pytest_args:
        description: 'Pytest arguments'
        # Default value if no value is explicitly provided
        default: ''
        required: false
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.5
    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: 3.12
    - name: install requirements
      run: pip install -r requirements.txt
    - name: run tests
      run: python3 -m pytest ${{ github.event.inputs.pytest_args }}
    - name: zip test results and log files
      run: zip -r logs_and_reports.zip logs reports
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        path: |
          logs_and_reports.zip

    
    
